/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentfeedbacksystem;
import java.sql.*;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author roneetmichael
 */
public class RatingScreen extends javax.swing.JFrame {

    /**
     * Creates new form RatingScreen
     */
    public RatingScreen(){}
    public RatingScreen(String username) {
        initComponents();
        updateTable();
        jLabel_rs.setText(username);
    }
    private void updateTable()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "studentfeedback"); 
            Statement stm = con.createStatement();
            String coursename = "select course_name from courses";
           // String coursecode = "select course_code from courses";

            ResultSet rs = stm.executeQuery(coursename);
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("course_name"));               
            }
            
        } catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        coursecodeui = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        feedback_submit_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        question2_slider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        question1_slider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        question4_slider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        question5_slider = new javax.swing.JSlider();
        jLabel_rs = new javax.swing.JLabel();
        write_feedback_field = new javax.swing.JTextField();
        question3_slider1 = new javax.swing.JSlider();
        close_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 232, 240));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N

        label1.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(61, 90, 254));
        label1.setText("Choose a Subject");

        coursecodeui.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        coursecodeui.setForeground(new java.awt.Color(102, 102, 102));
        coursecodeui.setText("Choose the subject from dropdown list");

        jLabel1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("The lecture was clear and easy to understand");

        feedback_submit_button.setForeground(new java.awt.Color(61, 90, 254));
        feedback_submit_button.setText("Submit");
        feedback_submit_button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(61, 90, 254)));
        feedback_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_submit_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("The lecturer has good time management.");

        question2_slider.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        question2_slider.setMajorTickSpacing(1);
        question2_slider.setMaximum(10);
        question2_slider.setMinimum(1);
        question2_slider.setPaintLabels(true);
        question2_slider.setPaintTicks(true);
        question2_slider.setToolTipText("");
        question2_slider.setValue(5);

        jLabel3.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("The teaching method supports my learning process");

        question1_slider.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        question1_slider.setMajorTickSpacing(1);
        question1_slider.setMaximum(10);
        question1_slider.setMinimum(1);
        question1_slider.setPaintLabels(true);
        question1_slider.setPaintTicks(true);
        question1_slider.setToolTipText("");
        question1_slider.setValue(5);

        jLabel4.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Altogether, I am satisfied with the lecture. ");

        question4_slider.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        question4_slider.setMajorTickSpacing(1);
        question4_slider.setMaximum(10);
        question4_slider.setMinimum(1);
        question4_slider.setPaintLabels(true);
        question4_slider.setPaintTicks(true);
        question4_slider.setToolTipText("");
        question4_slider.setValue(5);

        jLabel6.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Leave A Note (Optional)");

        jLabel7.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("The lecture’s contents are comprehensible.");

        question5_slider.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        question5_slider.setMajorTickSpacing(1);
        question5_slider.setMaximum(10);
        question5_slider.setMinimum(1);
        question5_slider.setPaintLabels(true);
        question5_slider.setPaintTicks(true);
        question5_slider.setToolTipText("");
        question5_slider.setValue(5);

        jLabel_rs.setText("username");

        question3_slider1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        question3_slider1.setMajorTickSpacing(1);
        question3_slider1.setMaximum(10);
        question3_slider1.setMinimum(1);
        question3_slider1.setPaintLabels(true);
        question3_slider1.setPaintTicks(true);
        question3_slider1.setToolTipText("");
        question3_slider1.setValue(5);

        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel_rs))
                    .addComponent(coursecodeui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(319, 319, 319)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(question1_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(question2_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(319, 319, 319)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(question5_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(write_feedback_field, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(feedback_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question3_slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(question4_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_rs)))
                .addGap(10, 10, 10)
                .addComponent(coursecodeui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(question1_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(question2_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question3_slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question4_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question5_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(write_feedback_field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedback_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void feedback_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_submit_buttonActionPerformed
        // TODO add your handling code here:
        try{
        
        //String enroll = jLabel_rs.toString();
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "studentfeedback"); 
        
        //PreparedStatement stm = con.prepareStatement("INSERT INTO `student`.`feedback_info` (`enrollment`, `course_name`, `question_1`, `question_2`, `question_3`, `question_4`, `question_5`, `feedback_comment`) VALUES ('" + en +"', '" + course_name +"' , '" + q1 +"', '"+q2+"', '" + q3 +"', '" + q4 +"', '" + q5 +"', '" + feedback_text +"')");
        //PreparedStatement stm1 = con.prepareStatement("Update `student`.`feedback_info` SET 'course_code'=?");
        
        //System.out.println("Jlabel"+jLabel_rs);
        
        String en = jLabel_rs.getText().toString();
        String course_name = jComboBox1.getSelectedItem().toString();
        int q1 = question1_slider.getValue();
        int q2 = question2_slider.getValue();
        int q3 = question1_slider.getValue();
        int q4 = question4_slider.getValue();
        int q5 = question5_slider.getValue();
        String feedback_text = write_feedback_field.getText();
        PreparedStatement stm = con.prepareStatement("INSERT INTO `student`.`feedback_info` (`enrollment`, `course_name`, `question_1`, `question_2`, `question_3`, `question_4`, `question_5`, `feedback_comment`, `feedback_id` ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
        
        stm.setString(1, en);
        stm.setString(2, course_name);
        stm.setInt(3, q1);
        stm.setInt(4, q2);
        stm.setInt(5, q3);
        stm.setInt(6, q4);
        stm.setInt(7, q5);
        stm.setString(8, feedback_text);
        stm.setInt(9, 0);
        
        stm.executeUpdate();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "Submitted Successfully!");
       /* JFrame fr = new JFrame();
                    fr.setSize(400, 350);
                    fr.setTitle("Advance Details");
                    fr.setVisible(true);
                    int slipno=0;
                    ThankYou ck = new ThankYou();
                    ck.setBounds(50, 50, 900, 900);
                    fr.add(ck);
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    // this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
                    fr.setLocation(dim.width /10, dim.height / 10); */
        
        
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_feedback_submit_buttonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        Login ty = new Login();
        ty.show();
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RatingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RatingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RatingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RatingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RatingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton close_button;
    private java.awt.Label coursecodeui;
    private javax.swing.JButton feedback_submit_button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel_rs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private java.awt.Label label1;
    private javax.swing.JSlider question1_slider;
    private javax.swing.JSlider question2_slider;
    private javax.swing.JSlider question3_slider1;
    private javax.swing.JSlider question4_slider;
    private javax.swing.JSlider question5_slider;
    private javax.swing.JTextField write_feedback_field;
    // End of variables declaration//GEN-END:variables
}
